# Site Settings
title: Andrew Haines
email: andrew.m.haines@gmail.com
description: >
  I do things
#baseurl: "/andrewhain.es"
#url: "https://andrewhaines.github.io"
url: "http://andrewhain.es"
twitter_username: am_haines
github_username:  andrewhaines
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
