# Site Settings
title: Andrew Haines
email: andrew.m.haines@gmail.com
description: >
  I do things
baseurl: ""
url: "http://localhost:4000"
twitter_username: am_haines
github_username:  andrewhaines
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
